name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Authenticate with GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Assign reviewer
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python .github/scripts/assign_reviewer.py
